export default {
  SET_USER: "SET_USER",
  LOG_OUT: "LOG_OUT",
  POST_USER_DATA_REQUEST: "POST_USER_DATA_REQUEST",
  POST_USER_DATA_SUCCESS: "POST_USER_DATA_SUCCESS",
  POST_USER_DATA_FAILURE: "POST_USER_DATA_FAILURE",
};
